export const DISCOVER_SCREEN = "DISCOVER_SCREEN";
export const MAP_SCREEN = "MAP_SCREEN";
export const ADD_LOCATION_SCREEN = "ADD_LOCATION_SCREEN";
export const LIKED_LOCATIONS_SCREEN = "LIKED_LOCATIONS_SCREEN";
export const PROFILE_SCREEN = "PROFILE_SCREEN";
