export const PROFILE_SCREEN_NO_AUTH_MAIN_SCREEN =
  "PROFILE_SCREEN_NO_AUTH_MAIN_SCREEN";
export const PROFILE_SCREEN_LOGIN_SCREEN = "PROFILE_SCREEN_LOGIN_SCREEN";
export const PROFILE_SCREEN_REGISTER_SCREEN = "PROFILE_SCREEN_REGISTER_SCREEN";
